Fizzbuzz課題の提出
AyakaTakashima/ruby-practices pull request #1
Opened 2021-07-26 09:33 UTC by AyakaTakashima

自分のmainにプルリクを作成しました。
ご確認よろしくお願いいたします。

2021-07-26 18:23 UTC, summertree128 reviewed
レビューしました！

動作的にはバッチリなんですが、`if`分岐の作り方には改善の余地がありそうなのでぜひ考えてみてもらいたいです。

現状だと12行目や15行目に`unless`が必要になってしまっていますが、これらは実は書く必要がありません 💡  ただし全体の構造を少し変えてやる必要があります。

ヒントというか答えに近いですが、`elsif`を使って全体的に書き換えてみてもらいたいです。そうすればそもそもこのプログラムに`unless`を登場させる必要はなくなり、より簡潔なコードにすることができます。

「どうすれば最もシンプルな形の実装にできるか」を念頭に置きつつ、`elsif`を使った形に書き直してみてください 🙏

2021-07-26 18:23 UTC, summertree128 commented on 01.fizzbuzz/fizzbuzz.rb
> +	unless x%3==0||x%5==0
Rubyでは慣習的にインデントの一レベルを半角スペース2個分とすることがほとんどなので、是非この慣習に従っていきましょう 💡 
それから、演算子を書くときは演算子の前後に半角スペースを空けるのも一般的な慣習ですのでこちらもやっていきましょう。

これらを踏まえてこの行を修正すると以下のような感じになります。
```suggestion
  unless x % 3 == 0 || x % 5 == 0
```
他の行も同様に修正をお願いします 🙏

2021-07-26 18:25 UTC, summertree128 commented on 01.fizzbuzz/fizzbuzz.rb
> +			puts "Buzz" unless x%3==0
そもそもこの行を書き直すことになるとは思いますが、ここだけインデントがずれてますね。（タブが一つ多い）
同じ階層のコードは同じインデントに揃えましょう〜

2021-07-27 13:09 UTC, AyakaTakashima commented
elsif文に修正しました！
ご確認よろしくお願いいたします！

2021-07-28 10:57 UTC, summertree128 requested changes
`elsif`の導入でかなりスッキリして良くなりましたね！ 👍 

あと一つだけ考えてもらいたいこととして、`if`を使うときは`else`も書いて処理を対称的にするのが基本になります。

`if`の中身は何かの条件を満たす時の処理なので、その条件を満たさない時はどうなるか？ということを`else`に書く必要があります。（条件を満たさない場合は何もしない、という場合は`else`は不要ですが）

Fizzbuzzの場合だと、条件というのは3で割り切れるとかそういうやつで、条件を満たさない時は数値をそのまま出力すればいいということになりますよね。
こういうのは大体厳しい条件から順番に見ていけば良いので、日本語で書き下すとこんな感じになるんじゃないかと思います。

- 3でも5でも割り切れたら"Fizzbuzz"と表示
- 3で割り切れたら"Fizz"と表示
- 5で割り切れたら"Buzz"と表示
- 3でも5でも割り切れなかったら（つまりすべての条件を満たさなかったら）数値をそのまま表示

…ということで、`if`〜`elsif`の最後に`else`が来る形に書き直してみてください 💡

2021-07-29 09:56 UTC, AyakaTakashima commented
ありがとうございます！
スペースについてですが、フィヨルドのプラクティスにもあったので[このサイト](https://dev.classmethod.jp/articles/change-default-indent-in-vscode/)のようにtabをスペースふたつ分に設定しています。

![image](https://user-images.githubusercontent.com/76944527/127471202-01103888-d0a5-46a0-b0ef-840cdbe1a0f9.png)

それでもgithubに反映されないのは仕方のないことなんでしょうか…
毎回tabキーではなくスペースを2回打たなくてはいけないのでしょうか😢

2021-07-30 12:44 UTC, summertree128 commented
> ありがとうございます！
> スペースについてですが、フィヨルドのプラクティスにもあったので[このサイト](https://dev.classmethod.jp/articles/change-default-indent-in-vscode/)のようにtabをスペースふたつ分に設定しています。
> 
> ![image](https://user-images.githubusercontent.com/76944527/127471202-01103888-d0a5-46a0-b0ef-840cdbe1a0f9.png)
> 
> それでもgithubに反映されないのは仕方のないことなんでしょうか…
> 毎回tabキーではなくスペースを2回打たなくてはいけないのでしょうか😢



タブという単語がちょっとややこしいのですが、何も設定しなかった場合、Tabキーを押したときには「タブ文字」と呼ばれる文字が入力されます。タブ文字はターミナルやブラウザによってどのくらいの幅で表示されるかが異なるという特殊な文字です。これは「ハードタブ」と呼ばれたりもします。

これに対して、Tabキーを押したときにタブ文字ではなく半角スペースが入力されるようなやりかたを「ソフトタブ」と言います。

上記のスクリーンショットの設定は、ソフトタブを行う際に「タブキーを一度押したときに入力する半角スペースの数」を設定されていますね。
これはこれでいいのですが、それ以前にまずハードタブを行う設定になってしまっているのではないでしょうか？
「タブキーを押したときにタブ文字を入力するか半角スペースを入力するか」みたいな感じの設定項目があったと思うので、探してみてください🙏

2021-07-30 12:51 UTC, summertree128 approved these changes
とても簡潔なコードになりましたね！レビューOKです〜 👍

2021-08-02 10:02 UTC, merged